import = ["~/.config/alacritty/themes/dracula.toml"]

[env]
TERM = "xterm-256color"

[window]
blur = true
opacity = 0.85

[font]
normal = { family = "FiraCode NerdFont", style = "Regular" }
size = 12
